let pilares = {
  pilar1: {
    name: "Pilar I: FORMACIÓN INTEGRAL",
    propuestas: [
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      // {
      //   title: "Propuesta 4",
      //   desc: "4 This is a very long description",
      //   problematica: "propblemática de la propuesta",
      //   propuesta: "Propuesta de la propuesta",
      //   estrategias: "estrategias de la propuesta",
      // },
    ],
  },
  pilar2: {
    name: "Pilar II: INVESTIGACIÓN - RSU",
    propuestas: [
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
    ],
  },
  pilar3: {
    name: "Pilar III: GESTIÓN ESTRATÉGICA",
    propuestas: [
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 5",
        desc: "5 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
    ],
  },
  pilar4: {
    name: "Pilar IV: SOPORTE INSTITUCIONAL",
    propuestas: [
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 1",
        desc: "1 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 2",
        desc: "2 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 3",
        desc: "3 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
      {
        title: "Propuesta 4",
        desc: "4 This is a very long description",
        problematica: "propblemática de la propuesta",
        propuesta: "Propuesta de la propuesta",
        estrategias: "estrategias de la propuesta",
      },
    ],
  },
}
